export enum SelectCardAction {
  ADD = 'ADD',
  CARDNUMSELECTED = 'CARDNUMSELECTED',
  CARDHOLDERFIRST = 'CARDHOLDERFIRST',
  CARDHOLDERSECOND = 'CARDHOLDERSECOND',
  EXPIRATIONDATE_YEAR = 'EXPIRATIONDATE_YEAR',
  EXPIRATIONDATE_MONTH = 'EXPIRATIONDATE_MONTH',
  CARDCVCSELECTED = 'CARDCVCSELECTED',
  DOWNLOADINPUT = 'DOWNLOADINPUT',
  INITIALIZATION = 'INITIALIZATION'
}

export enum CardActionValidate {
  CARDVALIDATE = 'CARDVALIDATE'
}
