export enum SelectCardAction {
  ADD = "ADD",
  CARDNUMSELECTED = "CARDNUMSELECTED",
  CARDHOLDETRSELECTED = "CARDHOLDETRSELECTED",
  EXPIRATIONDATE_YEAR = "EXPIRATIONDATE_YEAR",
  EXPIRATIONDATE_MONTH = "EXPIRATIONDATE_MONTH",
  CARDCVCSELECTED = "CARDCVCSELECTED",
}
